# Generated by Django 4.2.17 on 2025-01-09 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='latitude',
            field=models.FloatField(default=42.8746),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='longitude',
            field=models.FloatField(default=74.5698),
        ),
        migrations.AddField(
            model_name='request',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
