# Generated by Django 4.2.17 on 2025-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='waste_types',
            field=models.CharField(choices=[('plastic', 'Пластик'), ('paper', 'Бумага'), ('metal', 'Металл'), ('glass', 'Стекло'), ('medical', 'Медицинские отходы'), ('construction', 'Строительные отходы'), ('agricultural', 'Сельские отходы')], max_length=50, verbose_name='Тип отходов'),
        ),
    ]
