# Generated by Django 4.2.17 on 2025-01-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collectionpoint_latitude_collectionpoint_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='request_photos/'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
