# Generated by Django 4.2.17 on 2025-01-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_collectionpoint_waste_types_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
